version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    volumes:
      - app_data:/app/data  
    depends_on:
      - db
      # - redis


    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  # redis:
  #     image: redis
   
  
  celery-worker:
      build: 
        context: .
        dockerfile: Dockerfile
      command : bash -c "celery -A video_upload  worker --pool=solo -l info"  
      depends_on:
          - db
          # - redis

  # celery-beat:
  #       restart: always
  #       build: 
  #         context: .
  #         dockerfile: Dockerfile
  #       command : bash -c "celery -A  video_upload beat -l info "
  #       ports: 
  #       - "6379:6379"
  #       depends_on:
  #         - redis
  #         - db




  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data 


 


volumes:
  app_data: 
  postgres_data:  

