version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - app_data:/app/data  
    networks:
      - my_network
    depends_on:
      - db
    command: >
      bash -c "
      echo 'DB_NAME: $DB_NAME'
      echo 'DB_USER: $DB_USER'
      echo 'DB_PASSWORD: $DB_PASSWORD'
      python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8002"
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  app_data: 
  postgres_data:  

networks:
  my_network:  
